CREATE TABLE IF NOT EXISTS USERS
(
USER_ID INT PRIMARY KEY AUTO_INCREMENT,
EMAIL VARCHAR(255) NOT NULL,
LOGIN VARCHAR(255) NOT NULL,
USER_NAME VARCHAR(255) NOT NULL,
BIRTHDAY DATE
);

CREATE TABLE IF NOT EXISTS FILMS
(
FILM_ID INT PRIMARY KEY AUTO_INCREMENT,
TITLE VARCHAR(255) NOT NULL,
DESCRIPTION VARCHAR(255) NOT NULL,
RELEASE_DATE DATE,
MPA_id INT,
DURATION INT
);

CREATE TABLE IF NOT EXISTS USERS_FILMS_LIKES
(
User_id INT NOT NULL,
Film_id INT NOT NULL,
CONSTRAINT pk_users_films_likes PRIMARY KEY (User_id, Film_id),
FOREIGN KEY (User_id) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
FOREIGN KEY (Film_id) REFERENCES FILMS(FILM_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FRIENDSHIP
(
User_id INT NOT NULL,
Friend_id INT NOT NULL,
Status_id INT NOT NULL,
CONSTRAINT pk_friendship PRIMARY KEY (User_id, Friend_id),
FOREIGN KEY (User_id) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
FOREIGN KEY (Friend_id) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FILM_GENRES
(
    FILM_ID  INT NOT NULL,
    GENRE_ID INT NOT NULL,
    CONSTRAINT pk_film_genres PRIMARY KEY (FILM_ID, GENRE_ID),
    FOREIGN KEY (FILM_ID) REFERENCES FILMS(FILM_ID) ON DELETE CASCADE
);

